"use client"
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Navbar from "./../components/layout/Navbar";
import AppProvider from "@/components/AppContext";
import { SessionProvider } from "next-auth/react";
const roboto= Roboto({ subsets: ["latin"],weight: ['400','500','700']});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-screen-xl	 mx-auto ">
         
          <Navbar/>
          {children}
          <Footer/>
          
          </main>
          </body>
    </html>
  );
}
